taxiapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'taxiapp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<taxi_id>[0-9]+)$', views.edit, name='edit'),
    url(r'^(?P<taxi_id>[0-9]+)/update$', views.update, name='update'),
    url(r'^create/', views.create, name='create'),
    url(r'^store/', views.store, name='store'),
]

travelapp/urls.py
from django.conf import settings
from django.conf.urls import url, include

from django.conf.urls.static import static
from rest_framework import routers

from taxiapp import views

router = routers.DefaultRouter()
router.register(r'taxis', views.TaxiViewSet)

urlpatterns = [
  url(r'^', include(router.urls)),
  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxiapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Taxi(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20, null=True, blank=True)
    open_hour = models.TimeField()
    close_hour = models.TimeField()
    logo = models.ImageField(upload_to='uploads/')
    stars = models.IntegerField(default=0)

    def __str__(self):
        return self.name

taxiapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from rest_framework import viewsets

from taxiapp.models import Taxi
from taxiapp.serializers import TaxiSerializer


class TaxiViewSet(viewsets.ModelViewSet):
    queryset = Taxi.objects.all().order_by('-stars')
    serializer_class = TaxiSerializer


def create(request):
    return render(request, 'taxiapp/create.html')


def store(request):
    # print request.POST
    taxi = Taxi()
    taxi.name = request.POST['name']
    taxi.phone = request.POST['phone']
    taxi.open_hour = request.POST['open_hour']
    taxi.close_hour = request.POST['close_hour']
    taxi.save()

    return HttpResponseRedirect(reverse('taxiapp:index'))


def edit(request, taxi_id):
    # Method 1
    # try:
    #     taxi = Taxi.objects.get(pk=taxi_id)
    # except Taxi.DoesNotExist:
    #     raise Http404("Taxi does not exist")

    # Method 2
    taxi = get_object_or_404(Taxi, pk=taxi_id)

    return render(request, 'taxiapp/edit.html', {'taxi': taxi})


def update(request, taxi_id):
    try:
        taxi = Taxi.objects.get(pk=taxi_id)
    except Taxi.DoesNotExist:
        raise Http404("Taxi does not exist")

    taxi.name = request.POST['name']
    taxi.phone = request.POST['phone']
    taxi.open_hour = request.POST['open_hour']
    taxi.close_hour = request.POST['close_hour']
    taxi.save()

    return HttpResponseRedirect(reverse('taxiapp:index'))


class IndexView(generic.ListView):
    template_name = 'taxiapp/index.html'
    context_object_name = 'taxis'

    def get_queryset(self):
        return Taxi.objects.order_by('-stars')

taxiapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}My amazing site{% endblock %}</title>
    <!-- Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="/static/taxiapp/materialize/css/materialize.css">
    <link rel="stylesheet" href="/static/taxiapp/style.css">
</head>
<body>
<nav>
    <div class="nav-wrapper">
        <a href="#" class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li class="{% if request.get_full_path == '/taxi/' %} active{% endif %}"><a href="{% url 'taxiapp:index' as home_url %}">Order Taxi</a></li>
            <li class="{% if request.get_full_path == 'weather' %} active{% endif %}" ><a href="#">Weather</a></li>
            <li class="{% if request.get_full_path == 'journeys' %} active{% endif %}"><a href="#">Journeys</a></li>
        </ul>
    </div>
</nav>

<div class="container">
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</div>


{% load static %}
<!-- Compiled and minified JavaScript -->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="/static/taxiapp/materialize/js/materialize.js"></script>
<script src="/static/taxiapp/app.js"></script>

</body>
</html>

taxiapp/templates/taxiapp/create.html
{% extends "base.html" %}

{% block title %}Register new taxi{% endblock %}

{% block content %}
<h1>Register new taxi</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="row">
    <form action="{% url 'taxiapp:store' %}" method="post" class="col s12">
        {% csrf_token %}
        <div class="input-field col s12">
            <input type="text" id="name_input" name="name">
            <label for="name_input">Name</label>
        </div>
        <div class="input-field col s12">
            <input type="text" id="phone_input" name="phone">
            <label for="phone_input">Phone</label>
        </div>
        <div class="input-field col s6">
            <input type="datetime" name="open_hour" id="open_hour_input" class="timepicker">
            <label for="open_hour_input">Open Hour</label>
        </div>
        <div class="input-field col s6">
            <input type="datetime" name="close_hour" id="close_hour_input" class="timepicker">
            <label for="close_hour_input">Close Hour</label>
        </div>
        <div class="input-field col s12">
            <button class="btn waves-effect waves-light" type="submit" name="action">
                Register
                <i class="material-icons right">send</i>
            </button>
        </div>
    </form>
</div>

{% endblock %}

taxiapp/templates/taxiapp/edit.html
{% extends "base.html" %}

{% block title %}Update taxi{% endblock %}

{% block content %}
<h1>Edit {{taxi.name}}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="row">
    <form action="{% url 'taxiapp:update' taxi.id %}" method="post" class="col s12">
        {% csrf_token %}
        <div class="input-field col s12">
            <input type="text" id="name_input" name="name" value="{{taxi.name}}">
            <label for="name_input">Name</label>
        </div>
        <div class="input-field col s12">
            <input type="text" id="phone_input" name="phone" value="{{taxi.phone}}">
            <label for="phone_input">Phone</label>
        </div>
        <div class="input-field col s6">
            <input type="datetime" value="{{taxi.open_hour}}" name="open_hour" id="open_hour_input" class="timepicker">
            <label for="open_hour_input" class="active">Open Hour</label>
        </div>
        <div class="input-field col s6">
            <input type="datetime" value="{{taxi.close_hour}}" name="close_hour" id="close_hour_input" class="timepicker">
            <label for="close_hour_input" class="active">Close Hour</label>
        </div>
        <div class="input-field col s12">
            <a class="btn waves-effect waves-light" href="{% url 'taxiapp:index' %}" name="action">
                Back
                <i class="material-icons right">replay</i>
            </a>
            <button class="btn waves-effect waves-light" type="submit" name="action">
                Register
                <i class="material-icons right">send</i>
            </button>
        </div>
    </form>
</div>

{% endblock %}

taxiapp/templates/taxiapp/index.html
{% extends "base.html" %}

{% block title %}Taxis{% endblock %}

{% block content %}

{% if taxis %}
<h2 class="header">Order your taxi</h2>
<div class="row">
    {% for taxi in taxis %}
    <div class="col s6">
        <div class="card">
            <div class="card-stacked">
                <div class="card-image">
                    <img src="http://materializecss.com/images/sample-1.jpg">
                    <span class="card-title">{{taxi.name}}</span>
                    <a href="tel:{{taxi.phone}}" class="btn-floating halfway-fab waves-effect waves-light red"><i
                            class="material-icons">call</i></a>
                </div>
                <div class="card-content">
                    <p>Open: {{ taxi.open_hour }} - {{ taxi.close_hour }}</p>
                    <p>Phone: {{taxi.phone}}</p>
                    <p>Rating: {{taxi.stars}}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'taxiapp:edit' taxi.id %}"><i class="material-icons">mode_edit</i>Edit</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

{% endblock %}